Add elm-review
guida-lang/compiler pull request #20
Opened 2024-09-15 17:54 UTC by MartinSStewart

This completes https://github.com/guida-lang/compiler/issues/4. I disabled most of the default rules for now. I think it's a better idea to incrementally enable rules rather than try to manage one enormous diff in this PR. Also removing unused code across the entire repo probably isn't a good idea at this stage since there seems to be a lot of code that belongs to disabled parts of the compiler and presumably will be needed when re-enabling those parts later.

2024-09-15 23:15 UTC, decioferreira requested changes
Thank you so much for this work @MartinSStewart 🙏❤️ I fully agree with this approach of disabled some of the rules for now and incrementally re-enabling them (thanks for thinking of this aspect).

I've made a few comments on the code, see if they all make sense.

I've also noticed that the format seems to be a little bit off, can you please confirm from your side by running something like `npx elm-format . --yes`?

Thanks again for your help!

2024-09-15 23:15 UTC, decioferreira commented on terminal/src/Develop/Socket.elm
> +a = 0
do we need this?

2024-09-15 23:15 UTC, decioferreira commented on terminal/src/Develop/Socket.elm
> +--watchFile watchedFile pendingConnection =
find it strange that we can comment out a function that is exposed, is this okay?

2024-09-15 23:15 UTC, decioferreira commented on compiler/src/Reporting/Doc.elm
> +            Debug.toString (P.pretty 0 doc)
not sure if we should remove this `Debug.log`, the `encode` function has not yet been implemented, and I'm not sure if we could convert this into a `Debug.todo`. Maybe we should consider making this an exception on the configuration?

2024-09-16 10:07 UTC, MartinSStewart commented on terminal/src/Develop/Socket.elm
> +a = 0
If we don't have one declaration in the module then elm-review won't be able to parse it. That's why I commented out the existing code.

2024-09-16 10:08 UTC, MartinSStewart commented on terminal/src/Develop/Socket.elm
> +--watchFile watchedFile pendingConnection =
This module and a few others have a bunch of errors that prevent them from compiling. But they aren't used by the compiler so we don't get any errors. I just did the minimum to make it so elm-review won't failing when parsing them.

2024-09-16 21:14 UTC, decioferreira approved these changes

2024-09-16 21:22 UTC, merged

2024-09-16 21:23 UTC, decioferreira commented
Thank you 💯